# Prometheus Configuration
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'shell-platform'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "alert_rules.yml"
  - "recording_rules.yml"

# A scrape configuration for running Prometheus on a host.
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s
    metrics_path: /metrics

  # Node Exporter - System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    metrics_path: /metrics

  # cAdvisor - Container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
    metrics_path: /metrics

  # Shell Platform API Gateway
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:3001']
    scrape_interval: 15s
    metrics_path: /metrics
    scheme: http

  # File Service
  - job_name: 'file-service'
    static_configs:
      - targets: ['file-service:3002']
    scrape_interval: 15s
    metrics_path: /metrics
    scheme: http

  # External API Service
  - job_name: 'external-api-service'
    static_configs:
      - targets: ['external-api-service:3003']
    scrape_interval: 15s
    metrics_path: /metrics
    scheme: http

  # Frontend Shell
  - job_name: 'frontend-shell'
    static_configs:
      - targets: ['frontend-shell:5173']
    scrape_interval: 30s
    metrics_path: /metrics
    scheme: http

  # Database metrics (if using postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 15s
    metrics_path: /metrics

  # Redis metrics (if using redis_exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 15s
    metrics_path: /metrics

  # Elasticsearch metrics
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']
    scrape_interval: 30s
    metrics_path: /_prometheus/metrics
    scheme: http

  # Nginx metrics (if using nginx-prometheus-exporter)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 15s
    metrics_path: /metrics

  # Application health checks
  - job_name: 'health-checks'
    static_configs:
      - targets: 
        - 'api-gateway:3001'
        - 'file-service:3002'
        - 'external-api-service:3003'
    scrape_interval: 30s
    metrics_path: /health
    scheme: http

  # Custom business metrics
  - job_name: 'business-metrics'
    static_configs:
      - targets: ['api-gateway:3001']
    scrape_interval: 60s
    metrics_path: /metrics/business
    scheme: http

# Remote storage configuration (optional - for long-term storage)
# remote_write:
#   - url: "https://prometheus-remote-write.example.com/api/v1/write"
#     basic_auth:
#       username: "username"
#       password: "password"

# Storage configuration
storage:
  tsdb:
    # Retention time for raw data
    retention_time: 30d
    # Maximum size of the storage
    retention_size: 10GB
    # Minimum block duration
    min_block_duration: 2h
    # Maximum block duration
    max_block_duration: 25h