# Grafana Datasources Configuration
apiVersion: 1

datasources:
  # Prometheus - Primary metrics source
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    basicAuth: false
    jsonData:
      httpMethod: POST
      queryTimeout: 60s
      timeInterval: 5s
      exemplarTraceIdDestinations:
        - name: traceID
          datasourceUid: jaeger

  # Elasticsearch - Logs source
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "[logs-]YYYY.MM.DD"
    basicAuth: false
    isDefault: false
    editable: true
    jsonData:
      interval: Daily
      timeField: '@timestamp'
      esVersion: '8.0.0'
      logMessageField: message
      logLevelField: level
      includeFrozen: false
      maxConcurrentShardRequests: 5

  # Jaeger - Distributed tracing
  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    uid: jaeger
    editable: true
    jsonData:
      tracesToLogs:
        datasourceUid: Elasticsearch
        tags: ['job', 'instance', 'pod', 'namespace']
        mappedTags: [{ key: 'service.name', value: 'service' }]
        mapTagNamesEnabled: false
        spanStartTimeShift: '-1h'
        spanEndTimeShift: '1h'
        filterByTraceID: false
        filterBySpanID: false
      nodeGraph:
        enabled: true
      spanBar:
        type: 'None'
      tracesToMetrics:
        datasourceUid: Prometheus
        tags: [{ key: 'service.name', value: 'service' }, { key: 'operation' }]
        queries:
          - name: 'Request rate'
            query: 'sum(rate(traces_spanmetrics_latency_bucket{$$__tags}[5m]))'
          - name: 'Error rate'
            query: 'sum(rate(traces_spanmetrics_latency_bucket{$$__tags,status_code="ERROR"}[5m]))'
          - name: 'Duration'
            query: 'histogram_quantile(0.9, sum(rate(traces_spanmetrics_latency_bucket{$$__tags}[5m])) by (le))'

  # InfluxDB for high-frequency metrics (optional)
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: shell_platform
    user: admin
    secureJsonData:
      password: password
    isDefault: false
    editable: true
    jsonData:
      httpMode: GET
      keepCookies: []