global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@shell-platform.local'

# Route defines the routing tree for alerts
route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'

# Receivers define how to send alerts
receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://localhost:5001/webhook'
        send_resolved: true

# Inhibit rules allow to mute alerts when other alerts are already firing
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']
